### ISSUE TITLE
ToDo List - strapi - BackEnd

### ISSUE THREAD

**Issue by ivopc** [ivopc/open-rifinha#2]
--- Strapi / BackEnd ---

- [ ] **(Main)** Schedule to release and close raffles cron job https://github.com/kelektiv/node-cron/
- [ ] **(Additional)** Handle errors for all routes in controllers !!IMPORTANT!!
- [ ] **(Additional)** Optimize all database queries !!IMPORTANT!! https://strapi.io/blog/understanding-and-using-relations-in-strapi
- [ ] **(Additional)** Use native web API features !!IMPORTANT!!
- [ ] **(Additional)** Optimize the query for the prize service `prize.findAllToDashboard` !!IMPORTANT!!
- [ ] **(Additional)** Change admin roles to control API access !!IMPORTANT!!
- [ ] **(Additional)** Clean up mobile phone number inputs, leaving only the numbers
- [ ] **(Additional)** Implement a request queue to generate tickets correctly in `/api/purchases/is-paid` https://github.com/sindresorhus/p-queue
- [ ] **(Additional)** Improve the system for generating tickets randomly and generate a list of available tickets if the generated ticket already exists, instead of picking something random to avoid locking the event loop within the `generateNewTicket` function
- [ ] **(Additional)** Security: hpp, helmet
